import { logout } from "@/app/(admin)/admin/actions";
import { ImportForm } from "@/components/admin/ImportForm";
import { SubmitButton } from "@/components/admin/SubmitButton";
import { GlassCard } from "@/components/ui/glass-card";
import { requireAdminSession } from "@/lib/admin-auth";
import { getCurrentImportVersion } from "@/lib/admin-import";

export default async function AdminPage() {
  await requireAdminSession();
  const currentImportVersion = await getCurrentImportVersion();

  return (
    <div className="grid w-full gap-6 lg:grid-cols-[minmax(0,0.72fr)_minmax(19rem,0.28fr)]">
      <GlassCard className="rounded-[2rem] border border-white/10 bg-white/7 p-7 sm:p-8">
        <p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary/80">
          Import
        </p>
        <h2 className="mt-3 font-heading text-3xl font-semibold tracking-tight text-white">
          Apply a scrape export
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">
          Upload a JSON export generated by the trusted source machine, or paste the
          payload directly. The frontend verifies your admin session, then forwards
          the request to the private Rust import route with the internal secret.
        </p>

        <div className="mt-8">
          <ImportForm />
        </div>
      </GlassCard>

      <div className="space-y-6">
        <GlassCard className="rounded-[2rem] border border-white/10 bg-white/7 p-6">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary/80">
            Current version
          </p>
          {currentImportVersion.currentVersion !== null ? (
            <>
              <p className="mt-3 font-heading text-4xl font-semibold tracking-tight text-white">
                {currentImportVersion.currentVersion}
              </p>
              <p className="mt-3 text-sm leading-6 text-muted-foreground">
                The next incremental import must use scrape run version{" "}
                <span className="font-semibold text-white">
                  {currentImportVersion.currentVersion + 1}
                </span>
                .
              </p>
            </>
          ) : (
            <>
              <p className="mt-3 font-heading text-2xl font-semibold tracking-tight text-white">
                Unavailable
              </p>
              <p className="mt-3 text-sm leading-6 text-muted-foreground">
                {currentImportVersion.error}
              </p>
            </>
          )}
        </GlassCard>

        <GlassCard className="rounded-[2rem] border border-white/10 bg-white/7 p-6">
          <h2 className="font-heading text-xl font-semibold text-white">
            Session controls
          </h2>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            The admin cookie is HTTP-only, scoped to <code>/admin</code>, and expires
            after one hour.
          </p>

          <form action={logout} className="mt-5">
            <SubmitButton
              idleLabel="Sign out"
              pendingLabel="Signing out..."
              variant="outline"
            />
          </form>
        </GlassCard>

        <GlassCard className="rounded-[2rem] border border-white/10 bg-white/7 p-6">
          <h2 className="font-heading text-xl font-semibold text-white">
            Import notes
          </h2>
          <ul className="mt-3 space-y-3 text-sm leading-6 text-muted-foreground">
            <li>Use a snapshot first on a fresh production database.</li>
            <li>Use force only for deliberate gap recovery.</li>
            <li>The backend response is shown below the form after each run.</li>
          </ul>
        </GlassCard>
      </div>
    </div>
  );
}
