export const COUNTRY_GROUPS: {
  label: string;
  options: { label: string; value: string }[];
}[] = [
  {
    label: "North America",
    options: [
      { label: "United States", value: "US" },
      { label: "Canada", value: "CA" },
      { label: "Mexico", value: "MX" },
      { label: "Puerto Rico", value: "PR" },
    ],
  },
  {
    label: "Europe",
    options: [
      { label: "United Kingdom", value: "GB" },
      { label: "Germany", value: "DE" },
      { label: "France", value: "FR" },
      { label: "Spain", value: "ES" },
      { label: "Norway", value: "NO" },
      { label: "Sweden", value: "SE" },
      { label: "Italy", value: "IT" },
      { label: "Finland", value: "FI" },
      { label: "Denmark", value: "DK" },
      { label: "Netherlands", value: "NL" },
      { label: "Belgium", value: "BE" },
      { label: "Switzerland", value: "CH" },
      { label: "Austria", value: "AT" },
      { label: "Poland", value: "PL" },
      { label: "Portugal", value: "PT" },
      { label: "Czech Republic", value: "CZ" },
      { label: "Hungary", value: "HU" },
      { label: "Romania", value: "RO" },
      { label: "Bulgaria", value: "BG" },
      { label: "Greece", value: "GR" },
      { label: "Croatia", value: "HR" },
      { label: "Slovenia", value: "SI" },
      { label: "Slovakia", value: "SK" },
      { label: "Serbia", value: "RS" },
      { label: "Bosnia and Herzegovina", value: "BA" },
      { label: "Lithuania", value: "LT" },
      { label: "Latvia", value: "LV" },
      { label: "Estonia", value: "EE" },
      { label: "Iceland", value: "IS" },
      { label: "Ireland", value: "IE" },
    ],
  },
  {
    label: "Asia Pacific",
    options: [
      { label: "Australia", value: "AU" },
      { label: "New Zealand", value: "NZ" },
      { label: "Japan", value: "JP" },
      { label: "South Korea", value: "KR" },
      { label: "Taiwan", value: "TW" },
      { label: "Hong Kong", value: "HK" },
      { label: "Thailand", value: "TH" },
      { label: "Malaysia", value: "MY" },
      { label: "Singapore", value: "SG" },
      { label: "Philippines", value: "PH" },
    ],
  },
  {
    label: "Middle East & Africa",
    options: [
      { label: "UAE", value: "AE" },
      { label: "Turkey", value: "TR" },
      { label: "Israel", value: "IL" },
      { label: "Saudi Arabia", value: "SA" },
      { label: "Qatar", value: "QA" },
      { label: "Oman", value: "OM" },
      { label: "Morocco", value: "MA" },
    ],
  },
  {
    label: "Latin America",
    options: [
      { label: "Chile", value: "CL" },
      { label: "Colombia", value: "CO" },
      { label: "Uruguay", value: "UY" },
    ],
  },
];
